# Generated by Django 4.0.4 on 2022-05-28 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner_id', models.IntegerField()),
                ('topic1', models.TextField()),
                ('topic2', models.TextField(blank=True, null=True)),
                ('topic3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.TextField()),
                ('belongs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.IntegerField()),
                ('topic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=150, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Eメールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='ユーザーステータス')),
                ('password', models.CharField(max_length=15, verbose_name='パスワード')),
            ],
        ),
    ]
