# Generated by Django 4.0.4 on 2022-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='partner_id',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
